"""xlwings integration layer for the standalone pyqlite pricing package."""

from pyqlite_xlwings.functions import (
    PYQL_CAPFLOOR_NPV,
    PYQL_DIGITAL_FX_OPTION_NPV,
    PYQL_FIXED_BOND_NPV,
    PYQL_FLOAT_FLOAT_NPV,
    PYQL_FRA_NPV,
    PYQL_FX_FORWARD_NPV,
    PYQL_FX_FORWARD_RATE,
    PYQL_FX_FORWARD_ZERO_NPV_RATE,
    PYQL_FX_OPTION_NPV,
    PYQL_NONSTANDARD_SWAP_NPV,
    PYQL_OIS_FAIR_RATE,
    PYQL_OIS_NPV,
    PYQL_SWAPTION_NPV,
    PYQL_SWAP_FAIR_RATE,
    PYQL_SWAP_NPV,
)

__all__ = [
    "PYQL_CAPFLOOR_NPV",
    "PYQL_DIGITAL_FX_OPTION_NPV",
    "PYQL_FIXED_BOND_NPV",
    "PYQL_FLOAT_FLOAT_NPV",
    "PYQL_FRA_NPV",
    "PYQL_FX_FORWARD_NPV",
    "PYQL_FX_FORWARD_RATE",
    "PYQL_FX_FORWARD_ZERO_NPV_RATE",
    "PYQL_FX_OPTION_NPV",
    "PYQL_NONSTANDARD_SWAP_NPV",
    "PYQL_OIS_FAIR_RATE",
    "PYQL_OIS_NPV",
    "PYQL_SWAPTION_NPV",
    "PYQL_SWAP_FAIR_RATE",
    "PYQL_SWAP_NPV",
]
